#!/usr/bin/env bash
set -euo pipefail

log_run()
{
    echo >&2 "+ $*"
    "$@"
}

main()
{
    VERSION=$1
    if [[ ! $VERSION =~ ^v[0-9]\.[0-9]\.[0-9]$ ]]; then
            echo >&2 "Invalid version. Expected v1.2.3 or so"
        exit 1
    fi

    log_run sed -i'' 's/^\(BTRFS_AUTO_SNAPSHOT_VERSION\)=.*/\1='"$VERSION/" btrfs-auto-snapshot
    log_run git add btrfs-auto-snapshot
    log_run git commit -m "Release $VERSION"
    log_run git tag "$VERSION"
    log_run sed -i'' 's/^\(BTRFS_AUTO_SNAPSHOT_VERSION\)=.*/\1='"$VERSION+dev/" btrfs-auto-snapshot
    log_run git add btrfs-auto-snapshot
    log_run git commit -m "$VERSION+dev"
    echo "You have tagged $VERSION. Now run the following:"
    echo "  git push origin master"
    echo "  git push origin $VERSION"
}

main "$@"
